### PR TITLE
feat: `MacroTask` eventloop

### PR DESCRIPTION
**Pull request by marc2332**
Requires https://github.com/trynova/nova/pull/348

### CODE REVIEW

**Comment by marc2332** [comment]
We really need a runtime abstracion so we can clean up the cli `main.rs` it is becoming a mess

**Comment by marc2332** [comment]
I need to implement an async tasks tracker in order to decide whether the event loop should exit or not.

**Comment by marc2332** [comment]
> I need to implement an async tasks tracker in order to decide whether the event loop should exit or not.

Done

**Review by load1n9 — APPROVED** [review]
LGTM

**Pull request merged**
